# Generated by Django 6.0.5 on 2026-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Autor', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Stock', models.PositiveIntegerField()),
            ],
        ),
    ]
